# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Robert Simcoe
title: International Accountant
email: robert.simcoe.jr@gmail.com
website: https://rsimcoe.github.io

# Social links
# twitter_username: facespics
github_username:  rsimcoe
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: robert-simcoe-bbb22732
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Robert and I'm a finance professional and a data enthusiast with 6 years of expirence, based in Kansas City, Missouri. I am currently working for Water.org as an international accountant supporting our offices in Africa and Latin America. Apart from my accounting work, I am tasked with maintaining our leadership's dashboard in Power BI along with providing ad-hoc reporting/analysis to key stakeholders in the organization.

  Insert something here about stuff I like doing; Challenging work, learning, exploring data, etc.

  I am most skilled in:  <mark>Power BI</mark>, <mark>Excel</mark>,<mark>Customer Something</mark>, and <mark>WHAT ELSE ARE YOU GOOD AT</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in finance and data/analyics some of my other interests and hobbies are:
   - Cycling
   - Gaming
   - Personal Finance

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
